[Desktop]
DesktopShortcuts=Home, Trash, Computer, Network
Wallpaper=/usr/share/lxqt/themes/hyggshios-light/Verdant-Valley.png
WallpaperMode=zoom
WallpaperRandomize=false

[System]
Archiver=xarchiver
FallbackIconThemeName=tela-circle-light
Terminal=qterminal

[Window]
AlwaysShowTabs=true
